image: $CI_IMAGE

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - lint
    - build

before_script:
    - mkdir -p build
    - ln -s /build/toolchain_iree_rv32imf ./build/toolchain_iree_rv32imf
    - ln -s /build/iree_compiler ./build/iree_compiler
    - export PATH=${HOME}/.local/bin:${PATH}
    - build_tools/configure_cmake.sh -G Ninja

format:
    stage: lint
    script:
        - cmake --build build/build-riscv --target format
    allow_failure: false

build:
    stage: build
    script:
        - cmake --build build/build-riscv
    allow_failure: false
