image: $CI_IMAGE

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - lint
    - build

before_script:
    - mkdir -p build
    - ln -s /build/toolchain_iree_rv32imf ./build/toolchain_iree_rv32imf
    - ln -s /build/iree_compiler ./build/iree_compiler
    - export PATH=${HOME}/.local/bin:${PATH}


format:
    stage: lint
    script:
        - build_tools/format.sh
    allow_failure: false

build:
    stage: build
    script:
        - build_tools/build.sh
    allow_failure: false
