image: $CI_IMAGE

variables:
    GIT_STRATEGY: clone

stages:
    - lint
    - build
    - tests

.build_prepare: &build_prepare
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        GIT_SUBMODULE_DEPTH: 1
        GIT_SUBMODULE_UPDATE_FLAGS: --jobs `nproc`
    before_script:
        - mkdir -p build
        - ln -s /opt/toolchain_iree_rv32imf ./build/toolchain_iree_rv32imf
        - ln -s /opt/iree_compiler ./build/iree_compiler
        - export PATH=${HOME}/.local/bin:${PATH}
        - build_tools/configure_cmake.sh -G Ninja

.minimal_build_prepare: &minimal_build_prepare
    variables:
        GIT_SUBMODULE_STRATEGY: none
    before_script:
        - cmake -B build/build-riscv -G Ninja -DMINIMAL_BUILD=True

clang_format:
    stage: lint
    <<: *minimal_build_prepare
    script:
        - cmake --build build/build-riscv --target clang-format

clang_tidy:
    stage: lint
    <<: *minimal_build_prepare
    variables:
        GIT_SUBMODULE_STRATEGY: normal
    script:
        - git -C third-party/iree-rv32-springbok submodule update --init
        - cmake --build build/build-riscv --target clang-tidy

build:
    stage: build
    <<: *build_prepare
    script:
        - cmake --build build/build-riscv
    artifacts:
        paths:
        - build/build-riscv/iree-runtime/iree_runtime

unit_tests:
    stage: tests
    <<: *minimal_build_prepare
    script:
        - cmake --build build/build-riscv --target unit-tests

renode_tests:
    stage: tests
    <<: *minimal_build_prepare
    variables:
        GIT_SUBMODULE_STRATEGY: normal
    script:
        - ln -s /opt/renode ./build/renode
        - cmake --build build/build-riscv --target renode-tests
        - ./renode-tests/render_kenning_report.sh
    artifacts:
        paths:
        - renode-tests/results/robot_output.xml
        - renode-tests/results/log.html
        - renode-tests/results/report.html
        - renode-tests/results/opcode_stats.txt
        - renode-tests/results/kenning_output.json
        - renode-tests/results/benchmarks/
        when: always
