image: ubuntu:latest

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - lint
    - build

format:
    stage: lint
    script:
        - apt-get update
        - apt-get install -y git xxd cmake ninja-build wget python3 python3-pip clang-format
        - python3 -m pip install requests wget numpy pillow
        - third-party/iree-rv32-springbok/build_tools/install_toolchain.sh
        - python3 third-party/iree-rv32-springbok/build_tools/download_iree_compiler.py
        - export PATH=${HOME}/.local/bin:${PATH}
        - build_tools/format.sh
    allow_failure: false

build:
    stage: build
    script:
        - apt-get update
        - apt-get install -y git xxd cmake ninja-build wget python3 python3-pip
        - python3 -m pip install requests wget numpy pillow
        - third-party/iree-rv32-springbok/build_tools/install_toolchain.sh
        - python3 third-party/iree-rv32-springbok/build_tools/download_iree_compiler.py
        - export PATH=${HOME}/.local/bin:${PATH}
        - build_tools/build.sh
    allow_failure: false
