name: Kenning bare-metal IREE runtime tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    cancel-previous-job:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel previous
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}
    readme-tests:
        runs-on: ubuntu-latest
        container:
            image: debian:bullseye
        steps:
            - name: Install tuttest dependencies
              run: |
                  apt-get update -qqy
                  apt-get install -qqy --no-install-recommends python3 python3-pip git git-lfs colorized-logs sudo
                  pip3 install git+https://github.com/antmicro/tuttest.git
            - name: Checkout sources
              uses: actions/checkout@v4
              with:
                  lfs: true
            - name: Update submodules
              run: |
                  ./build_tools/configure_git_url_rewrite.sh
                  git submodule update --init --recursive
            - name: Run README.md snippets
              run: |
                  ./.github/scripts/readme-tests.sh
            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: gh-page
                  path: report-html
            - name: Deploy to Github Pages
              if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
              run: |
                  cd report-html
                  cp report.html index.html
                  touch .nojekyll
                  git init
                  cp ../.git/config ./.git/config
                  git add .
                  git config --local user.email "push@gha"
                  git config --local user.name "GHA"
                  git commit -am "update ${{ github.sha }}"
                  git push -u origin +HEAD:gh-pages
                  rm -rf .git
